// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvZyn5elINNBJ6Xvp4Y8kFgqFOcvTUFQ',
    appId: '1:612913751535:web:90633b43ed6a92fff2c21a',
    messagingSenderId: '612913751535',
    projectId: 'petstrackers',
    authDomain: 'petstrackers.firebaseapp.com',
    storageBucket: 'petstrackers.appspot.com',
    measurementId: 'G-EYLN84YD0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC31OalsZc4AhePIcwU21o6DdhIdeHK9Q',
    appId: '1:612913751535:android:f844bd5948529747f2c21a',
    messagingSenderId: '612913751535',
    projectId: 'petstrackers',
    storageBucket: 'petstrackers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl7d8sR-uC9MM3PfSvkRI1IFQUPNMiJBA',
    appId: '1:612913751535:ios:4fba8b48566dae4cf2c21a',
    messagingSenderId: '612913751535',
    projectId: 'petstrackers',
    storageBucket: 'petstrackers.appspot.com',
    iosClientId: '612913751535-ckkn14ekmcbn5mi2c471hvsmbpqb344a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pets',
  );
}
